### ISSUE TITLE
reram or sram?

### ISSUE THREAD

**Issue by GitDiscipline** [lekez2005/opennvram-reram#1]
Hi, 
   How have you created the instances of reram using OpenRAM?

**Comment by lekez2005** [comment]
It's a forked version of OpenRAM that's been very heavily modified. You can explore sample GDS for various array sizes at https://github.com/lekez2005/sky130_reram_caravel/tree/main/gds

**Comment by mguthaus** [comment]
Is it possible to get the modifications in openram so that you can benefit from other updates that we are doing? We could make openreram.py using the API.

**Comment by lekez2005** [comment]
I mostly consider this repo read-only, I created it specifically for the shuttle. As I said, there has been a lot of divergence so lots of git cherry-picking will need to be done to eventually upstream my changes. To make that happen, I'll be pushing another repo that has all of the previous git history so it's easier to see what's changed. I still need to ensure no proprietary information leaks through the git history so I still need to do some clean up before I can push it. 

We can further discuss how to upstream once I have the main repo up. In the mean time, if you find anything useful in the repo as it is, feel free to use...
