### ISSUE TITLE
no gds files for sky130

### ISSUE THREAD

**Issue by Samarthjainabout** [lekez2005/opennvram-reram#5]
I noted the sky130 dont have gds files. then how is modified reram open ram is compiling all elements?
![image](https://user-images.githubusercontent.com/30805083/230722165-589198da-763d-46b0-8f06-f5384a8540a0.png)

**Comment by lekez2005** [comment]
It generates its own custom gds for all peripherals at run-time. There are infact two gds files in the sky130 gds technology directory but those are specific to reram and caravel:

> `ls $OPENRAM_TECH/sky130/gds_lib`
> `sky130_fd_pr__reram_reram_cell.gds  user_analog_project_wrapper_empty.gds`

**Comment by Samarthjainabout** [comment]
In case i want to update the sense amp circuit, how can I edit the gds then if its runtime?

**Comment by lekez2005** [comment]
You can modify https://github.com/lekez2005/opennvram-reram/blob/main/technology/sky130/modules/reram_sense_amp.py directly
